<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class BaranggaysTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        DB::table('baranggays')->truncate();
        Schema::enableForeignKeyConstraints();

        $baranggays = [
            /**
             * ANGELES
             */
            ['name' => "Agapito del Rosario", 'location_id' => '1'],
            ['name' => "Anunas", 'location_id' => '1'],
            ['name' => "Balibago", 'location_id' => '1'],
            ['name' => "Capaya", 'location_id' => '1'],
            ['name' => "Claro M. Recto", 'location_id' => '1'],
            ['name' => "Cuayan", 'location_id' => '1'],
            ['name' => "Cutcut", 'location_id' => '1'],
            ['name' => "Cutud", 'location_id' => '1'],
            ['name' => "Lourdes North West", 'location_id' => '1'],
            ['name' => "Lourdes Sur", 'location_id' => '1'],
            ['name' => "Lourdes Sur East", 'location_id' => '1'],
            ['name' => "Malabanias", 'location_id' => '1'],
            ['name' => "Margot", 'location_id' => '1'],
            ['name' => "Mining", 'location_id' => '1'],
            ['name' => "Pampang", 'location_id' => '1'],
            ['name' => "Pandan", 'location_id' => '1'],
            ['name' => "Pulung Maragul", 'location_id' => '1'],
            ['name' => "Pulungbulu", 'location_id' => '1'],
            ['name' => "Pulung Cacutud", 'location_id' => '1'],
            ['name' => "Salapungan", 'location_id' => '1'],
            ['name' => "San Jose", 'location_id' => '1'],
            ['name' => "San Nicolas", 'location_id' => '1'],
            ['name' => "Santa Teresita", 'location_id' => '1'],
            ['name' => "Santa Trinidad", 'location_id' => '1'],
            ['name' => "Santo Cristo", 'location_id' => '1'],
            ['name' => "Santo Domingo", 'location_id' => '1'],
            ['name' => "Santo Rosario (Pob.)", 'location_id' => '1'],
            ['name' => "Sapalibutad", 'location_id' => '1'],
            ['name' => "Sapangbato", 'location_id' => '1'],
            ['name' => "Tabun", 'location_id' => '1'],
            ['name' => "Virgen Delos Remedios", 'location_id' => '1'],
            ['name' => "Amsic", 'location_id' => '1'],
            ['name' => "Ninoy Aquino (Marisol)", 'location_id' => '1'],

            /**
             * APALIT
             */

            ['name' => "Balucuc", 'location_id' => '2'],
            ['name' => "Calantipe", 'location_id' => '2'],
            ['name' => "Cansinala", 'location_id' => '2'],
            ['name' => "Capalangan", 'location_id' => '2'],
            ['name' => "Colgante", 'location_id' => '2'],
            ['name' => "Paligui", 'location_id' => '2'],
            ['name' => "Sampaloc", 'location_id' => '2'],
            ['name' => "San Juan (Pob.)", 'location_id' => '2'],
            ['name' => "San Vicente", 'location_id' => '2'],
            ['name' => "Sucad", 'location_id' => '2'],
            ['name' => "Sulipan", 'location_id' => '2'],
            ['name' => "Tabuyuc (Santo Rosario)", 'location_id' => '2'],
                    
            /**
             * ARAYAT
             */

            ['name' => "Arenas", 'location_id' => '3'],
            ['name' => "Baliti", 'location_id' => '3'],
            ['name' => "Batasan", 'location_id' => '3'],
            ['name' => "Buensuceso", 'location_id' => '3'],
            ['name' => "Candating", 'location_id' => '3'],
            ['name' => "Gatiawin", 'location_id' => '3'],
            ['name' => "Guemasan", 'location_id' => '3'],
            ['name' => "La Paz (Turu)", 'location_id' => '3'],
            ['name' => "Lacmit", 'location_id' => '3'],
            ['name' => "Lacquios", 'location_id' => '3'],
            ['name' => "Mangga-Cacutud", 'location_id' => '3'],
            ['name' => "Mapalad", 'location_id' => '3'],
            ['name' => "Panlinlang", 'location_id' => '3'],
            ['name' => "Paralaya", 'location_id' => '3'],
            ['name' => "Plazang Luma", 'location_id' => '3'],
            ['name' => "Poblacion", 'location_id' => '3'],
            ['name' => "San Agustin Norte", 'location_id' => '3'],
            ['name' => "San Agustin Sur", 'location_id' => '3'],
            ['name' => "San Antonio", 'location_id' => '3'],
            ['name' => "San Jose Mesulo", 'location_id' => '3'],
            ['name' => "San Juan Bano", 'location_id' => '3'],
            ['name' => "San Mateo", 'location_id' => '3'],
            ['name' => "San Nicolas", 'location_id' => '3'],
            ['name' => "San Roque Bitas", 'location_id' => '3'],
            ['name' => "Cupang (Santa Lucia)", 'location_id' => '3'],
            ['name' => "Matamo (Santa Lucia)", 'location_id' => '3'],
            ['name' => "Santo Niño Tabuan", 'location_id' => '3'],
            ['name' => "Suclayin", 'location_id' => '3'],
            ['name' => "Telapayong", 'location_id' => '3'],
            ['name' => "Kaledian (Camba)", 'location_id' => '3'],

            /**
             * BACOLOR
             */

            ['name' => "Balas", 'location_id' => '4'],
            ['name' => "Cabalantian", 'location_id' => '4'],
            ['name' => "Cabambangan (Pob.)", 'location_id' => '4'],
            ['name' => "Cabetican", 'location_id' => '4'],
            ['name' => "Calibutbut", 'location_id' => '4'],
            ['name' => "Concepcion", 'location_id' => '4'],
            ['name' => "Dolores", 'location_id' => '4'],
            ['name' => "Duat", 'location_id' => '4'],
            ['name' => "Macabacle", 'location_id' => '4'],
            ['name' => "Magliman", 'location_id' => '4'],
            ['name' => "Maliwalu", 'location_id' => '4'],
            ['name' => "Mesalipit", 'location_id' => '4'],
            ['name' => "Parulog", 'location_id' => '4'],
            ['name' => "Potrero", 'location_id' => '4'],
            ['name' => "San Antonio", 'location_id' => '4'],
            ['name' => "San Isidro", 'location_id' => '4'],
            ['name' => "San Vicente", 'location_id' => '4'],
            ['name' => "Santa Barbara", 'location_id' => '4'],
            ['name' => "Santa Ines", 'location_id' => '4'],
            ['name' => "Talba", 'location_id' => '4'],
            ['name' => "Tinajero", 'location_id' => '4'],

            /*** CANDABA ***/

            ['name' => "Bahay Pare", 'location_id' => '5'],
            ['name' => "Bambang", 'location_id' => '5'],
            ['name' => "Barangca", 'location_id' => '5'],
            ['name' => "Barit", 'location_id' => '5'],
            ['name' => "Buas (Pob.)", 'location_id' => '5'],
            ['name' => "Cuayang Bugtong", 'location_id' => '5'],
            ['name' => "Dalayap", 'location_id' => '5'],
            ['name' => "Dulong Ilog", 'location_id' => '5'],
            ['name' => "Gulap", 'location_id' => '5'],
            ['name' => "Lanang", 'location_id' => '5'],
            ['name' => "Lourdes", 'location_id' => '5'],
            ['name' => "Magumbali", 'location_id' => '5'],
            ['name' => "Mandasig", 'location_id' => '5'],
            ['name' => "Mandili", 'location_id' => '5'],
            ['name' => "Mangga", 'location_id' => '5'],
            ['name' => "Mapaniqui", 'location_id' => '5'],
            ['name' => "Paligui", 'location_id' => '5'],
            ['name' => "Pangclara", 'location_id' => '5'],
            ['name' => "Pansinao", 'location_id' => '5'],
            ['name' => "Paralaya (Pob.)", 'location_id' => '5'],
            ['name' => "Pasig", 'location_id' => '5'],
            ['name' => "Pescadores (Pob.)", 'location_id' => '5'],
            ['name' => "Pulong Gubat", 'location_id' => '5'],
            ['name' => "Pulong Palazan", 'location_id' => '5'],
            ['name' => "Salapungan", 'location_id' => '5'],
            ['name' => "San Agustin (Pob.)", 'location_id' => '5'],
            ['name' => "Santo Rosario", 'location_id' => '5'],
            ['name' => "Tagulod", 'location_id' => '5'],
            ['name' => "Talang", 'location_id' => '5'],
            ['name' => "Tenejero", 'location_id' => '5'],
            ['name' => "Vizal San Pablo", 'location_id' => '5'],
            ['name' => "Vizal Santo Cristo", 'location_id' => '5'],
            ['name' => "Vizal Santo Niño", 'location_id' => '5'],

            /*** FLORIDABLANCA ***/

            ['name' => "Anon", 'location_id' => '7'],
            ['name' => "Apalit", 'location_id' => '7'],
            ['name' => "Basa Air Base", 'location_id' => '7'],
            ['name' => "Benedicto", 'location_id' => '7'],
            ['name' => "Bodega", 'location_id' => '7'],
            ['name' => "Cabangcalan", 'location_id' => '7'],
            ['name' => "Calantas", 'location_id' => '7'],
            ['name' => "Carmencita", 'location_id' => '7'],
            ['name' => "Consuelo", 'location_id' => '7'],
            ['name' => "Dampe", 'location_id' => '7'],
            ['name' => "Del Carmen", 'location_id' => '7'],
            ['name' => "Fortuna", 'location_id' => '7'],
            ['name' => "Gutad", 'location_id' => '7'],
            ['name' => "Mabical", 'location_id' => '7'],
            ['name' => "Santo Rosario (Malabo)", 'location_id' => '7'],
            ['name' => "Maligaya", 'location_id' => '7'],
            ['name' => "Nabuclod", 'location_id' => '7'],
            ['name' => "Pabanlag", 'location_id' => '7'],
            ['name' => "Paguiruan", 'location_id' => '7'],
            ['name' => "Palmayo", 'location_id' => '7'],
            ['name' => "Pandaguirig", 'location_id' => '7'],
            ['name' => "Poblacion", 'location_id' => '7'],
            ['name' => "San Antonio", 'location_id' => '7'],
            ['name' => "San Isidro", 'location_id' => '7'],
            ['name' => "San Jose", 'location_id' => '7'],
            ['name' => "San Nicolas", 'location_id' => '7'],
            ['name' => "San Pedro", 'location_id' => '7'],
            ['name' => "San Ramon", 'location_id' => '7'],
            ['name' => "San Roque", 'location_id' => '7'],
            ['name' => "Santa Monica", 'location_id' => '7'],
            ['name' => "Solib", 'location_id' => '7'],
            ['name' => "Valdez", 'location_id' => '7'],
            ['name' => "Mawacat", 'location_id' => '7'],

            /*** GUAGUA ***/

            ['name' => "Bancal", 'location_id' => '8'],
            ['name' => "Jose Abad Santos (Siran)", 'location_id' => '8'],
            ['name' => "Lambac", 'location_id' => '8'],
            ['name' => "Magsaysay", 'location_id' => '8'],
            ['name' => "Maquiapo", 'location_id' => '8'],
            ['name' => "Natividad", 'location_id' => '8'],
            ['name' => "Plaza Burgos (Pob.)", 'location_id' => '8'],
            ['name' => "Pulungmasle", 'location_id' => '8'],
            ['name' => "Rizal", 'location_id' => '8'],
            ['name' => "San Agustin", 'location_id' => '8'],
            ['name' => "San Antonio", 'location_id' => '8'],
            ['name' => "San Isidro", 'location_id' => '8'],
            ['name' => "San Jose", 'location_id' => '8'],
            ['name' => "San Juan Bautista", 'location_id' => '8'],
            ['name' => "San Juan Nepomuceno", 'location_id' => '8'],
            ['name' => "San Matias", 'location_id' => '8'],
            ['name' => "San Miguel (Betis)", 'location_id' => '8'],
            ['name' => "San Nicolas 1st", 'location_id' => '8'],
            ['name' => "San Nicolas 2nd", 'location_id' => '8'],
            ['name' => "San Pablo", 'location_id' => '8'],
            ['name' => "San Pedro", 'location_id' => '8'],
            ['name' => "San Rafael (Duck Island)", 'location_id' => '8'],
            ['name' => "San Roque", 'location_id' => '8'],
            ['name' => "San Vicente (Ibus)", 'location_id' => '8'],
            ['name' => "San Juan", 'location_id' => '8'],
            ['name' => "Santa Filomena (Pob.)", 'location_id' => '8'],
            ['name' => "Santa Ines", 'location_id' => '8'],
            ['name' => "Santa Ursula", 'location_id' => '8'],
            ['name' => "Santo Cristo", 'location_id' => '8'],
            ['name' => "Santo Niño (Pob.)", 'location_id' => '8'],
            ['name' => "Ascomo", 'location_id' => '8'],

            /*** MABALACAT ***/

            ['name' => "Atlu-Bola", 'location_id' => '9'],
            ['name' => "Bical", 'location_id' => '9'],
            ['name' => "Bundagul", 'location_id' => '9'],
            ['name' => "Cacutud", 'location_id' => '9'],
            ['name' => "Calumpang", 'location_id' => '9'],
            ['name' => "Camachiles", 'location_id' => '9'],
            ['name' => "Dapdap", 'location_id' => '9'],
            ['name' => "Dau", 'location_id' => '9'],
            ['name' => "Dolores", 'location_id' => '9'],
            ['name' => "Duquit", 'location_id' => '9'],
            ['name' => "Lakandula", 'location_id' => '9'],
            ['name' => "Mabiga", 'location_id' => '9'],
            ['name' => "Macapagal Village", 'location_id' => '9'],
            ['name' => "Mamatitang", 'location_id' => '9'],
            ['name' => "Mangalit", 'location_id' => '9'],
            ['name' => "Marcos Village", 'location_id' => '9'],
            ['name' => "Mawaque", 'location_id' => '9'],
            ['name' => "Paralayunan", 'location_id' => '9'],
            ['name' => "Poblacion", 'location_id' => '9'],
            ['name' => "San Francisco", 'location_id' => '9'],
            ['name' => "San Joaquin", 'location_id' => '9'],
            ['name' => "Santa Ines", 'location_id' => '9'],
            ['name' => "Santa Maria", 'location_id' => '9'],
            ['name' => "Santo Rosario", 'location_id' => '9'],
            ['name' => "Sapang Balen", 'location_id' => '9'],
            ['name' => "Sapang Biabas", 'location_id' => '9'],
            ['name' => "Tabun", 'location_id' => '9'],

            /*** MACABEBE ***/
            ['name' => "Batasan", 'location_id' => '10'],
            ['name' => "Caduang Tete", 'location_id' => '10'],
            ['name' => "Candelaria", 'location_id' => '10'],
            ['name' => "Castuli", 'location_id' => '10'],
            ['name' => "Consuelo", 'location_id' => '10'],
            ['name' => "Dalayap", 'location_id' => '10'],
            ['name' => "Mataguiti", 'location_id' => '10'],
            ['name' => "San Esteban", 'location_id' => '10'],
            ['name' => "San Francisco", 'location_id' => '10'],
            ['name' => "San Gabriel (Pob.)", 'location_id' => '10'],
            ['name' => "San Isidro", 'location_id' => '10'],
            ['name' => "San Jose", 'location_id' => '10'],
            ['name' => "San Juan", 'location_id' => '10'],
            ['name' => "San Rafael", 'location_id' => '10'],
            ['name' => "San Roque", 'location_id' => '10'],
            ['name' => "San Vicente", 'location_id' => '10'],
            ['name' => "Santa Cruz (Pob.)", 'location_id' => '10'],
            ['name' => "Santa Lutgarda", 'location_id' => '10'],
            ['name' => "Santa Maria", 'location_id' => '10'],
            ['name' => "Santa Rita (Pob.)", 'location_id' => '10'],
            ['name' => "Santo Niño", 'location_id' => '10'],
            ['name' => "Santo Rosario (Pob.)", 'location_id' => '10'],
            ['name' => "Saplad David", 'location_id' => '10'],
            ['name' => "Tacasan", 'location_id' => '10'],
            ['name' => "Telacsan", 'location_id' => '10'],

            /*** MAGALANG ***/
            ['name' => "Camias", 'location_id' => '11'],
            ['name' => "Dolores", 'location_id' => '11'],
            ['name' => "Escaler", 'location_id' => '11'],
            ['name' => "La Paz", 'location_id' => '11'],
            ['name' => "Navaling", 'location_id' => '11'],
            ['name' => "San Agustin", 'location_id' => '11'],
            ['name' => "San Antonio", 'location_id' => '11'],
            ['name' => "San Franciso", 'location_id' => '11'],
            ['name' => "San Ildefonso", 'location_id' => '11'],
            ['name' => "San Isidro", 'location_id' => '11'],
            ['name' => "San Jose", 'location_id' => '11'],
            ['name' => "San Miguel", 'location_id' => '11'],
            ['name' => "San Nicolas 1st (Pob.)", 'location_id' => '11'],
            ['name' => "San Nicolas 2nd", 'location_id' => '11'],
            ['name' => "San Pablo (Pob.)", 'location_id' => '11'],
            ['name' => "San Pedro I", 'location_id' => '11'],
            ['name' => "San Pedro II", 'location_id' => '11'],
            ['name' => "San Roque", 'location_id' => '11'],
            ['name' => "San Vicente", 'location_id' => '11'],
            ['name' => "Santa Cruz (Pob.)", 'location_id' => '11'],
            ['name' => "Santa Lucia", 'location_id' => '11'],
            ['name' => "Santa Maria", 'location_id' => '11'],
            ['name' => "Santo Niño", 'location_id' => '11'],
            ['name' => "Santo Rosario", 'location_id' => '11'],
            ['name' => "Bucanan", 'location_id' => '11'],
            ['name' => "Turu", 'location_id' => '11'],
            ['name' => "Ayala", 'location_id' => '11'],

             /*** MASANTOL ***/
            ['name' => "Alauli", 'location_id' => '12'],
            ['name' => "Bagang", 'location_id' => '12'],
            ['name' => "Balibago", 'location_id' => '12'],
            ['name' => "Bebe Anac", 'location_id' => '12'],
            ['name' => "Bebe Matua", 'location_id' => '12'],
            ['name' => "Bulacus", 'location_id' => '12'],
            ['name' => "San Agustin (Caingin)", 'location_id' => '12'],
            ['name' => "Santa Monica (Caingin)", 'location_id' => '12'],
            ['name' => "Cambasi", 'location_id' => '12'],
            ['name' => "Malauli", 'location_id' => '12'],
            ['name' => "Nigui", 'location_id' => '12'],
            ['name' => "Palimpe", 'location_id' => '12'],
            ['name' => "Puti", 'location_id' => '12'],
            ['name' => "Sagrada (Tibagin)", 'location_id' => '12'],
            ['name' => "San Isidro Anac", 'location_id' => '12'],
            ['name' => "San Isidro Matua (Pob.)", 'location_id' => '12'],
            ['name' => "San Nicolas (Pob.)", 'location_id' => '12'],
            ['name' => "San Pedro", 'location_id' => '12'],
            ['name' => "Santa Cruz", 'location_id' => '12'],
            ['name' => "Santa Lucia Matua", 'location_id' => '12'],
            ['name' => "Santa Lucia Paguiba", 'location_id' => '12'],
            ['name' => "Santa Lucia Wakas", 'location_id' => '12'],
            ['name' => "Santa Lucia Anac (Pob.)", 'location_id' => '12'],
            ['name' => "Sapang Kawayan", 'location_id' => '12'],
            ['name' => "Sua", 'location_id' => '12'],
            ['name' => "Santo Niño", 'location_id' => '12'],

            /*** MEXICO ***/
            ['name' => "Acli", 'location_id' => '13'],
            ['name' => "Anao", 'location_id' => '13'],
            ['name' => "Balas", 'location_id' => '13'],
            ['name' => "Buenavista", 'location_id' => '13'],
            ['name' => "Camuning", 'location_id' => '13'],
            ['name' => "Cawayan", 'location_id' => '13'],
            ['name' => "Concepcion", 'location_id' => '13'],
            ['name' => "Culubasa", 'location_id' => '13'],
            ['name' => "Divisoria", 'location_id' => '13'],
            ['name' => "Dolores (Piring)", 'location_id' => '13'],
            ['name' => "Eden", 'location_id' => '13'],
            ['name' => "Gandus", 'location_id' => '13'],
            ['name' => "Lagundi", 'location_id' => '13'],
            ['name' => "Laput", 'location_id' => '13'],
            ['name' => "Laug", 'location_id' => '13'],
            ['name' => "Masamat", 'location_id' => '13'],
            ['name' => "Masangsang", 'location_id' => '13'],
            ['name' => "Nueva Victoria", 'location_id' => '13'],
            ['name' => "Pandacaqui", 'location_id' => '13'],
            ['name' => "Pangatlan", 'location_id' => '13'],
            ['name' => "Panipuan", 'location_id' => '13'],
            ['name' => "Parian (Pob.)", 'location_id' => '13'],
            ['name' => "Sabanilla", 'location_id' => '13'],
            ['name' => "San Antonio", 'location_id' => '13'],
            ['name' => "San Carlos", 'location_id' => '13'],
            ['name' => "San Jose Malino", 'location_id' => '13'],
            ['name' => "San Jose Matulid", 'location_id' => '13'],
            ['name' => "San Juan", 'location_id' => '13'],
            ['name' => "San Lorenzo", 'location_id' => '13'],
            ['name' => "San Miguel", 'location_id' => '13'],
            ['name' => "San Nicolas", 'location_id' => '13'],
            ['name' => "San Pablo", 'location_id' => '13'],
            ['name' => "San Patricio", 'location_id' => '13'],
            ['name' => "San Rafael", 'location_id' => '13'],
            ['name' => "San Roque", 'location_id' => '13'],
            ['name' => "San Vicente", 'location_id' => '13'],
            ['name' => "Santa Cruz", 'location_id' => '13'],
            ['name' => "Santa Maria", 'location_id' => '13'],
            ['name' => "Santo Domingo", 'location_id' => '13'],
            ['name' => "Santo Rosario", 'location_id' => '13'],
            ['name' => "Sapang Maisac", 'location_id' => '13'],
            ['name' => "Suclaban", 'location_id' => '13'],
            ['name' => "Tangle (Tanglay)", 'location_id' => '13'],

            /*** MINALIN ***/
            ['name' => "Bulac", 'location_id' => '14'],
            ['name' => "Dawe", 'location_id' => '14'],
            ['name' => "Lourdes", 'location_id' => '14'],
            ['name' => "Maniango", 'location_id' => '14'],
            ['name' => "San Francisco 1st", 'location_id' => '14'],
            ['name' => "San Francisco 2nd", 'location_id' => '14'],
            ['name' => "San Isidro", 'location_id' => '14'],
            ['name' => "San Nicolas (Pob.)", 'location_id' => '14'],
            ['name' => "San Pedro", 'location_id' => '14'],
            ['name' => "Santa Catalina", 'location_id' => '14'],
            ['name' => "Santa Maria", 'location_id' => '14'],
            ['name' => "Santa Rita", 'location_id' => '14'],
            ['name' => "Santo Domingo", 'location_id' => '14'],
            ['name' => "Santo Rosario (Pob.)", 'location_id' => '14'],
            ['name' => "Saplad", 'location_id' => '14'],

            /*** PORAC ***/
            ['name' => "Babo Pangulo", 'location_id' => '15'],
            ['name' => "Babo Sacan", 'location_id' => '15'],
            ['name' => "Balubad", 'location_id' => '15'],
            ['name' => "Calzadang Bayu", 'location_id' => '15'],
            ['name' => "Camias", 'location_id' => '15'],
            ['name' => "Cangatba", 'location_id' => '15'],
            ['name' => "Diaz", 'location_id' => '15'],
            ['name' => "Dolores (Hacienda Dolores)", 'location_id' => '15'],
            ['name' => "Jalung", 'location_id' => '15'],
            ['name' => "Mancatian", 'location_id' => '15'],
            ['name' => "Manibaug Libutad", 'location_id' => '15'],
            ['name' => "Manibaug Paralaya", 'location_id' => '15'],
            ['name' => "Manibaug Pasig", 'location_id' => '15'],
            ['name' => "Manuali", 'location_id' => '15'],
            ['name' => "Mitla Proper", 'location_id' => '15'],
            ['name' => "Palat", 'location_id' => '15'],
            ['name' => "Pias", 'location_id' => '15'],
            ['name' => "Pio", 'location_id' => '15'],
            ['name' => "Planas", 'location_id' => '15'],
            ['name' => "Poblacion", 'location_id' => '15'],
            ['name' => "Pulong Santol", 'location_id' => '15'],
            ['name' => "Salu", 'location_id' => '15'],
            ['name' => "San Jose Mitla", 'location_id' => '15'],
            ['name' => "Santa Cruz", 'location_id' => '15'],
            ['name' => "Sepung Bulaun", 'location_id' => '15'],
            ['name' => "Sinura", 'location_id' => '15'],
            ['name' => "Villa Maria (Aetas)", 'location_id' => '15'],
            ['name' => "Inararo (Aetas)", 'location_id' => '15'],
            ['name' => "Sapang Uwak (Aetas)", 'location_id' => '15'],

            /*** SAN FERNANDO ***/
            ['name' => "Alasas", 'location_id' => '16'],																						
            ['name' => "Baliti", 'location_id' => '16'],																						
            ['name' => "Bulaon", 'location_id' => '16'],																						
            ['name' => "Calulut", 'location_id' => '16'],																						
            ['name' => "Dela Paz Norte", 'location_id' => '16'],																						
            ['name' => "Dela Paz Sur", 'location_id' => '16'],																						
            ['name' => "Del Carmen", 'location_id' => '16'],																						
            ['name' => "Del Pilar", 'location_id' => '16'],																						
            ['name' => "Del Rosario", 'location_id' => '16'],																						
            ['name' => "Dolores", 'location_id' => '16'],																						
            ['name' => "Juliana", 'location_id' => '16'],																						
            ['name' => "Lara", 'location_id' => '16'],																						
            ['name' => "Lourdes", 'location_id' => '16'],																						
            ['name' => "Magliman", 'location_id' => '16'],																						
            ['name' => "Maimpis", 'location_id' => '16'],																						
            ['name' => "Malino", 'location_id' => '16'],																						
            ['name' => "Malpitic", 'location_id' => '16'],																						
            ['name' => "Pandaras", 'location_id' => '16'],																						
            ['name' => "Panipuan", 'location_id' => '16'],																						
            ['name' => "Santo Rosario (Pob.)", 'location_id' => '16'],																						
            ['name' => "Quebiauan", 'location_id' => '16'],																						
            ['name' => "Saguin", 'location_id' => '16'],																						
            ['name' => "San Agustin", 'location_id' => '16'],																						
            ['name' => "San Felipe", 'location_id' => '16'],																						
            ['name' => "San Isidro", 'location_id' => '16'],																						
            ['name' => "San Jose", 'location_id' => '16'],																						
            ['name' => "San Juan", 'location_id' => '16'],																						
            ['name' => "San Nicolas", 'location_id' => '16'],																						
            ['name' => "San Pedro", 'location_id' => '16'],																						
            ['name' => "Santa Lucia", 'location_id' => '16'],																						
            ['name' => "Santa Teresita", 'location_id' => '16'],																						
            ['name' => "Santo Niño", 'location_id' => '16'],																						
            ['name' => "Sindalan", 'location_id' => '16'],																						
            ['name' => "Telabastagan", 'location_id' => '16'],																						
            ['name' => "Pulung Bulu", 'location_id' => '16'],	
            
            /*** SAN LUIS ***/
            ['name' => "San Agustin", 'location_id' => '17'],
            ['name' => "San Carlos", 'location_id' => '17'],
            ['name' => "San Isidro", 'location_id' => '17'],
            ['name' => "San Jose", 'location_id' => '17'],
            ['name' => "San Juan", 'location_id' => '17'],
            ['name' => "San Nicolas", 'location_id' => '17'],
            ['name' => "San Roque", 'location_id' => '17'],
            ['name' => "San Sebastian", 'location_id' => '17'],
            ['name' => "Santa Catalina", 'location_id' => '17'],
            ['name' => "Santa Cruz Pambilog", 'location_id' => '17'],
            ['name' => "Santa Cruz Poblacion", 'location_id' => '17'],
            ['name' => "Santa Lucia", 'location_id' => '17'],
            ['name' => "Santa Monica", 'location_id' => '17'],
            ['name' => "Santa Rita", 'location_id' => '17'],
            ['name' => "Santo Niño", 'location_id' => '17'],
            ['name' => "Santo Rosario", 'location_id' => '17'],
            ['name' => "Santo Tomas", 'location_id' => '17'],

            /*** SAN SIMON ***/
            ['name' => "Concepcion", 'location_id' => '18'],
            ['name' => "De La Paz", 'location_id' => '18'],
            ['name' => "San Juan (Pob.)", 'location_id' => '18'],
            ['name' => "San Agustin", 'location_id' => '18'],
            ['name' => "San Isidro", 'location_id' => '18'],
            ['name' => "San Jose", 'location_id' => '18'],
            ['name' => "San Miguel", 'location_id' => '18'],
            ['name' => "San Nicolas", 'location_id' => '18'],
            ['name' => "San Pablo Libutad", 'location_id' => '18'],
            ['name' => "San Pablo Proper", 'location_id' => '18'],
            ['name' => "San Pedro", 'location_id' => '18'],
            ['name' => "Santa Cruz", 'location_id' => '18'],
            ['name' => "Santa Monica", 'location_id' => '18'],
            ['name' => "Santo Niño", 'location_id' => '18'],

            /*** SANTA ANA ***/
            ['name' => "San Agustin", 'location_id' => '19'],
            ['name' => "San Bartolome", 'location_id' => '19'],
            ['name' => "San Isidro", 'location_id' => '19'],
            ['name' => "San Joaquin (Pob.)", 'location_id' => '19'],
            ['name' => "San Jose", 'location_id' => '19'],
            ['name' => "San Juan", 'location_id' => '19'],
            ['name' => "San Nicolas", 'location_id' => '19'],
            ['name' => "San Pablo", 'location_id' => '19'],
            ['name' => "San Pedro", 'location_id' => '19'],
            ['name' => "San Roque", 'location_id' => '19'],
            ['name' => "Santa Lucia", 'location_id' => '19'],
            ['name' => "Santa Maria", 'location_id' => '19'],
            ['name' => "Santiago", 'location_id' => '19'],
            ['name' => "Santo Rosario", 'location_id' => '19'],

            /*** SANTO TOMAS ***/
            ['name' => "Moras De La Paz", 'location_id' => '20'],
            ['name' => "Poblacion", 'location_id' => '20'],
            ['name' => "San Bartolome", 'location_id' => '20'],
            ['name' => "San Matias", 'location_id' => '20'],
            ['name' => "San Vicente", 'location_id' => '20'],
            ['name' => "Santo Rosario (Pau)", 'location_id' => '20'],
            ['name' => "Sapa (Santo Niño)", 'location_id' => '20'],

            /*** SASMUAN ***/
            ['name' => "Batang 1st", 'location_id' => '21'],
            ['name' => "Batang 2nd", 'location_id' => '21'],
            ['name' => "Mabuanbuan", 'location_id' => '21'],
            ['name' => "Malusac", 'location_id' => '21'],
            ['name' => "Santa Lucia (Pob.)", 'location_id' => '21'],
            ['name' => "San Antonio", 'location_id' => '21'],
            ['name' => "San Nicolas 1st", 'location_id' => '21'],
            ['name' => "San Nicolas 2nd", 'location_id' => '21'],
            ['name' => "San Pedro", 'location_id' => '21'],
            ['name' => "Santa Monica", 'location_id' => '21'],
            ['name' => "Santo Tomas", 'location_id' => '21'],
            ['name' => "Sabitanan", 'location_id' => '21'],

            /*** LUBAO ***/
            ['name' => "Balantacan", 'location_id' => '22'],
            ['name' => "Bancal Sinubli", 'location_id' => '22'],
            ['name' => "Bancal Pugad", 'location_id' => '22'],
            ['name' => "Baruya (San Rafael)", 'location_id' => '22'],
            ['name' => "Calangain", 'location_id' => '22'],
            ['name' => "Concepcion", 'location_id' => '22'],
            ['name' => "Del Carmen", 'location_id' => '22'],
            ['name' => "De La Paz", 'location_id' => '22'],
            ['name' => "Don Ignacio Dimson", 'location_id' => '22'],
            ['name' => "Lourdes (Lauc Pau)", 'location_id' => '22'],
            ['name' => "Prado Siongco", 'location_id' => '22'],
            ['name' => "Remedios", 'location_id' => '22'],
            ['name' => "San Agustin", 'location_id' => '22'],
            ['name' => "San Antonio", 'location_id' => '22'],
            ['name' => "San Francisco", 'location_id' => '22'],
            ['name' => "San Isidro", 'location_id' => '22'],
            ['name' => "San Jose Apunan", 'location_id' => '22'],
            ['name' => "San Jose Gumi", 'location_id' => '22'],
            ['name' => "San Juan (Pob.)", 'location_id' => '22'],
            ['name' => "San Matias", 'location_id' => '22'],
            ['name' => "San Miguel", 'location_id' => '22'],
            ['name' => "San Nicolas 1st (Pob.)", 'location_id' => '22'],
            ['name' => "San Nicolas 2nd", 'location_id' => '22'],
            ['name' => "San Pablo 1st", 'location_id' => '22'],
            ['name' => "San Pablo 2nd", 'location_id' => '22'],
            ['name' => "San Pedro Palcarangan", 'location_id' => '22'],
            ['name' => "San Pedro Saug", 'location_id' => '22'],
            ['name' => "San Roque Arbol", 'location_id' => '22'],
            ['name' => "San Roque Dau", 'location_id' => '22'],
            ['name' => "San Vicente", 'location_id' => '22'],
            ['name' => "Santa Barbara", 'location_id' => '22'],
            ['name' => "Santa Catalina", 'location_id' => '22'],
            ['name' => "Santa Cruz", 'location_id' => '22'],
            ['name' => "Santa Lucia (Pob.)", 'location_id' => '22'],
            ['name' => "Santa Maria", 'location_id' => '22'],
            ['name' => "Santa Monica", 'location_id' => '22'],
            ['name' => "Santa Rita", 'location_id' => '22'],
            ['name' => "Santa Teresa 1st", 'location_id' => '22'],
            ['name' => "Santa Teresa 2nd", 'location_id' => '22'],
            ['name' => "Santiago", 'location_id' => '22'],
            ['name' => "Santo Domingo", 'location_id' => '22'],
            ['name' => "Santo Niño (Prado Aruba)", 'location_id' => '22'],
            ['name' => "Santo Tomas (Pob.)", 'location_id' => '22'],
            ['name' => "Santo Cristo", 'location_id' => '22'],

            /*** SANTA RITA ***/
            ['name' => "Becuran", 'location_id' => '23'],
            ['name' => "Dila-dila", 'location_id' => '23'],
            ['name' => "San Agustin", 'location_id' => '23'],
            ['name' => "San Basilio", 'location_id' => '23'],
            ['name' => "San Isidro", 'location_id' => '23'],
            ['name' => "San Jose (Pob.)", 'location_id' => '23'],
            ['name' => "San Juan", 'location_id' => '23'],
            ['name' => "San Matias", 'location_id' => '23'],
            ['name' => "San Vicente", 'location_id' => '23'],
            ['name' => "Santa Monica", 'location_id' => '23'],
        ];

        DB::table('baranggays')->insert($baranggays);
    }
}
